name: Windows Ubuntu macOS Builds

on:
    push:
        paths-ignore:
            - '**.md'
    pull_request:
        paths-ignore:
            - '**.md'
            - '**.yml'
            - '**.txt'

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
              os: [windows-latest, ubuntu-latest, macos-latest]
        env:
          BOOST_ROOT: ${{github.workspace}}/3rdparty/boost
          BOOST_URL: https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.bz2/download
        steps:
        - uses: actions/checkout@v2

        # Install boost - https://github.com/actions/virtual-environments/issues/2667#issuecomment-778655341
        - name: Restore Boost cache
          uses: actions/cache@v2
          id: cache-boost
          with:
            path: ${{env.BOOST_ROOT}}
            key: boost

        - name: Install Boost
          if: steps.cache-boost.outputs.cache-hit != 'true'
          run: |
            if ["OS" == "Windows_NT"]; then
              BOOST_ROOT=$(echo $BOOST_ROOT | sed 's/\\/\//g')
            fi
            mkdir -p $BOOST_ROOT
            curl --progress-bar --location --output $BOOST_ROOT/download.tar.bz2 $BOOST_URL
            7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar.bz2 -y -bd
            7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar -y -bd
            cd $BOOST_ROOT && cp -r boost_*/* .
            rm -rf boost_*/* download.tar.bz2 download.tar
          shell: bash

        - name: "Running CMAKE"
          run: |
            cd ${{ github.workspace }}
            mkdir build
            cd build
            cmake ../ -DITMF_TESTS=ON

        - name: "Building with CMAKE"
          run: |
            cd build
            cmake --build .

        - name: "Run tests"
          run: |
            cd build
            ctest